
server:
  port: 8002

spring:
  application:
    name: manage-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.51:3306/dream?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dream
    password: 1234

mybatis:
#  configuration:
#    multiple-result-sets-enabled: false
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: varchar
#    default-fetch-size: 500
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.dream.manage.dto


#logging:
#  file:
#    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
#    max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
#    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.
##  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
##    com.project.study : error
##    com.project.study.controller : debug
    
eureka:
  instance:
    instance-id: manage-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/api_gateway
         